### ISSUE TITLE
Keep getting 502 error (Caddy)

### ISSUE THREAD

**Issue by TheYsconator** [Zayon/dockerfiles#1]
Ahey! Thanks for converting TiddlyPWA to a Dockerfile.

I'm trying to use your container on my server, but for some reason I keep getting 502 errors. (Whilst other containers with a similar setup work properly.) I'm not too experienced with working with Dockerfiles (I generally just work with docker-compose files), but I did try 'expose'-ing port 8000, building, and using that new container. That sadly didn't resolve the problem.

I'm sure the error is on my side; probably due to my lack of understanding of Docker/Caddy. Though stilll; do you happen to have a pointer for me as to where I should start debugging?

My Caddyfile-entry for the subdomain is:

```Caddyfile
tiddlywiki.{$MY_DOMAIN} {
	reverse_proxy tiddlypwa:8000
}
```

And my docker-compose is:

```yml
version: "2"

services:
  tiddlypwa:
    image: zayon/tiddly-pwa:latest
    container_name: tiddlypwa
    hostname: tiddlypwa
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./tiddlypwa-data/:/var/db/tiddly

networks:
  external:
    name: $DOCKER_MY_NETWORK
```

And my .env:

```env
# GENERAL
<some general stuff>

# TIDDLYPWA
ADMIN_PASSWORD_HASH=<hash>
ADMIN_PASSWORD_SALT=<salt>
```

**Comment by Zayon** [comment]
Hello,

I'm glad if the docker image is useful to someone :)

I don't know Caddy myself as I use nginx but given it's a 502 error I don't think the issue comes from it.

What is the output of `docker logs tiddlypwa` ?

I think either the volume is causing write permissions errors or the network configuration is wrong, you might try:

```yaml
networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
```

**Comment by TheYsconator** [comment]
I must admit that I don't know what fixed the issue, but I used Composerize to convert your command from the README into a docker-compose file, and that did the trick. I'm now using:

```yml
version: '3.3'

services:
  tiddlypwa:
    image: zayon/tiddly-pwa:latest
    container_name: tiddlypwa
    hostname: tiddlypwa
    restart: unless-stopped
    env_file: .env
    volumes:
      - './tiddlypwa-data/:/var/db/tiddly'
    network_mode: $DOCKER_MY_NETWORK
```

So the issue seems to have been resolved; thanks!
